language: csharp
solution: culqi.net/culqi.net.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore culqi.net/culqi.net.sln
after_script:
  - nunit-console culqi.net/bin/Release/culqi.net.dll
